#!/bin/bash

# Global `ls` color file /etc/DIR_COLORS
if [ -f "/etc/DIR_COLORS" ]; then
        eval $(dircolors -b /etc/DIR_COLORS)
        fi

# Custom `ls` color file : ~/.dircolors
if [ -f "$HOME/.dircolors" ]; then
        eval $(dircolors -b ~/.dircolors)
        fi

# define color to additional file types
export LS_COLORS=$LS_COLORS:"*.wmv=01;35":"*.wma=01;35":"*.flv=01;35":"*.m4a=01;35"


############### COLOR DEFINITIONS ###############

# Define a few Colours
C_BLACK='\[\e[0;30m\]'
C_BLUE='\[\e[0;34m\]'
C_GREEN='\[\e[0;32m\]'
C_CYAN='\[\e[0;36m\]'
C_RED='\[\e[0;31m\]'
C_PURPLE='\[\e[0;35m\]'
C_BROWN='\[\e[0;33m\]'
C_LIGHTGRAY='\[\e[0;37m\]'
C_DARKGRAY='\[\e[1;30m\]'
C_LIGHTBLUE='\[\e[1;34m\]'
C_LIGHTGREEN='\[\e[1;32m\]'
C_LIGHTCYAN='\[\e[1;36m\]'
C_LIGHTRED='\[\e[1;31m\]'
C_LIGHTPURPLE='\[\e[1;35m\]'
C_YELLOW='\[\e[1;33m\]'
C_WHITE='\[\e[1;37m\]'
C_NC='\[\e[0m\]'              # No Color


C_DEF="\[\033[0m\]"
C_BLACK="\[\e[1;30m\]"
C_RED="\[\e[1;31m\]"
C_GREEN="\[\e[1;32m\]"
C_YELLOW="\[\e[1;33m\]"
C_BLUE="\[\e[1;34m\]"
C_PURPLE="\[\e[1;35m\]"
C_CYAN="\[\e[1;36m\]"
C_WHITE="\[\e[1;37m\]"

############### DISPLAY FORMAT ###############

case "$TERM" in
    xterm*|rxvt*)
        PS1="${C_YELLOW}[${C_DEF}${C_GREEN}\D{%H:%M:%S}${C_DEF}${C_YELLOW}]${C_DEF}${C_BLUE}\u${C_DEF}${C_YELLOW}@${C_DEF}${C_RED}\h${C_DEF}${C_YELLOW}${C_DEF} ${C_YELLOW}\w ${C_DEF}${C_BLUE}\$ ${C_DEF}"
        PS2="${C_BLUE}>${C_DEF} "
            ;;
        *)
            ;;
esac

